name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Create database
        run: mysql -uroot -proot -e "CREATE DATABASE botblock;"

      - name: Install dependencies
        run: npm install

      - name: Setup CI
        run: npm run ci:setup

      - name: Database migrations
        run: npm run db:migrate

      - name: Database seed
        run: npm run db:seed

      - name: Run CI
        run: npm run ci:run
